version: "3.1"

volumes:
  db:

services:
  database:
    image: mariadb:10.7
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: crdb
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d/
  backend:
    depends_on:
      - database
    restart: unless-stopped
    build: ./backend
    ports:
      - 8080:8080
  frontend:
    restart: unless-stopped
    build: ./frontend
    ports:
      - 4200:4200
